fs = 2000;
t1 = 0:1/fs:1-1/fs;
x_numeric = double(subs(x,t,t1));
y_numeric = double(subs(y,t,t1));
X_mag=abs(fft(x_numeric)); 
Y_mag=abs(fft(y_numeric));
figure(2);
subplot(2,1,1);
plot(t1,x_numeric); 
title("Input Signal");
xlabel("t (s)"); 
ylabel("x(t)"); 
subplot(2,1,2); 
plot(t1,y_numeric);
hold on;
title("Output Signal"); 
xlabel("t (s)"); 
ylabel("y(t)");
f1=fs*(0:length(x_numeric)-1)/length(x_numeric);
f2=fs*(0:length(y_numeric)-1)/length(y_numeric);
figure(3);
subplot(2,1,1);
plot(f1,X_mag);
title("Input Signal's Magnitude Spectrum"); 
xlabel("f (Hz)");
ylabel("|X(f)|");
hold on;
subplot(2,1,2);
plot(angle(fft(x_numeric)));
title("Input Signal's Phase Spectrum"); 
xlabel("f (Hz)");
ylabel("X(f) Phase");
figure(4);
subplot(2,1,1);
plot(f2,Y_mag);
hold on;
title("Output Signal's Magnitude Spectrum"); 
xlabel("f (Hz)");
ylabel("|Y(f)|");
subplot(2,1,2);
plot(angle(fft(y_numeric)));
title("Output Signal's Phase Spectrum"); 
xlabel("f (Hz)");
ylabel("Y(f) Phase");